### ISSUE TITLE
show the result in a new page

### ISSUE THREAD

**Issue by spsaswat** [spsaswat/plantdis#11]
Create a new page named model_results.dart, Instead of just showing the dialog box with the result.
In this page have a feedback box for the result.
![image](https://github.com/user-attachments/assets/d9dc7e73-efb4-4e43-9edf-ffc06a226d92)
Have another feedback field in the database as well.

**Comment by spsaswat** [comment]
![image](https://github.com/user-attachments/assets/899a6637-9d66-499c-8ccd-269c8568e703)

**Comment by Donutcheese** [comment]
![image](https://github.com/user-attachments/assets/e852ca5d-bb48-4e7e-8ed5-006c29bf3552)
![feedback_page](https://github.com/user-attachments/assets/7fc8f177-05ce-4c53-a74f-3006058acdb3)

**Comment by spsaswat** [comment]
Can you check the back button on the result screen it is taking some time or not working well.

**Comment by Donutcheese** [comment]
Yes, ill see how is going

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by spsaswat** [comment]
@Donutcheese, try showing a toast message like saving and navigating to home page.

**Comment by Donutcheese** [comment]
[Screen_recording_20240729_210159.webm](https://github.com/user-attachments/assets/fa2b3890-84b7-4ebd-8a57-a8aaf253ced4)

**Comment by spsaswat** [comment]
Thank @Donutcheese.
