### ISSUE TITLE
Improve app UI

### ISSUE THREAD

**Issue by spsaswat** [spsaswat/plantdis#4]
Add an app loader, and use toast/dialogue to show the result of disease classification. This can be achieved by editing the [main.dart](https://github.com/spsaswat/plantdis/blob/main/plantdis_mob/lib/main.dart) file. Please don't forget to add dependencies in the [YAML file](https://github.com/spsaswat/plantdis/blob/main/plantdis_mob/pubspec.yaml). Also, please add proper documentation to the code.

**Comment by spsaswat** [comment]
Also, reformat the result.
For example, Potato__Early_blight.
Reformat it as "The plant is Potato, and the disease is Early blight"
__ [double underscore as separator between plant and disease]

**Comment by Donutcheese** [comment]
![image](https://github.com/spsaswat/plantdis/assets/127721018/4eaa228e-5cec-4fb0-a2ca-c0f211ae45c9)
![image](https://github.com/spsaswat/plantdis/assets/127721018/81e2af88-e33c-45c4-8f47-d095c5df4315)
seperate to 2 situation, one for healthy plant and others for disease situation
