### ISSUE TITLE
Have a PlantDis app icon

### ISSUE THREAD

**Issue by spsaswat** [spsaswat/plantdis#7]
1. Try have a search icon over a diseased leaf

![image](https://github.com/spsaswat/plantdis/assets/45821961/77edd9ab-bda8-48c4-8d4b-1f162415e6f3)
2. Also, please add proper documentation to the code.

**Comment by Donutcheese** [comment]
![image](https://github.com/spsaswat/plantdis/assets/127721018/6a4327b3-8dae-4254-8758-0d46d3ffbc10)
the icon now looks like :
