### ISSUE TITLE
Connect the mobile app to firebase

### ISSUE THREAD

**Issue by spsaswat** [spsaswat/plantdis#8]
Store the result fo prediction (in firebase) and the image (under firebase storage)

**Comment by Donutcheese** [comment]
<img width="1212" alt="image" src="https://github.com/spsaswat/plantdis/assets/127721018/ac13c683-72da-43a7-970b-772eec924799">
<img width="1217" alt="image" src="https://github.com/spsaswat/plantdis/assets/127721018/813f756b-abe8-4d74-b457-bf911a775a63">
